import argparse
import json
import os
import pickle
from pathlib import Path

import numpy as np
import pandas as pd
import torch
from omegaconf import OmegaConf
from tqdm import tqdm

from src.metric import (
    evaluate_all_queries,
    summarize_metrics_by_organ,
    summarize_metrics_by_type,
)
from src.utils import (
    build_query_index_from_database_index,
    get_volume_id_from_slice_id,
    parse_gallery_query_key,
    retrieve_topk,
)


QUALITY_METRICS = {
    "relative_location": "relative_location",
    "relative_size": "relative_size",
    "bbox_iou": "bbox_iou",
    "lpips": "lpips",
    "ssim": "ssim",
    "mae": "mae",
    "wasserstein": "wasserstein",
}


def parse_args():
    parser = argparse.ArgumentParser(description="RCAT retrieval and evaluation.")
    parser.add_argument(
        "--config",
        type=str,
        default="./config/Model-Totalseg-RCAT.yaml",
    )
    parser.add_argument(
        "--database_index",
        type=str,
        default="./results/totalseg_database_gt_index.json",
    )
    parser.add_argument("--database_dir", type=str, default=None)
    parser.add_argument("--query_file", type=str, default=None)
    parser.add_argument("--mode", choices=["one", "multi", "full"], default="one")
    parser.add_argument("--n_regions", type=int, default=1)
    parser.add_argument("--n_samples", type=int, default=50)
    parser.add_argument("--n_queries", type=int, default=1000)
    parser.add_argument("--device", type=str, default=None)
    parser.add_argument(
        "--retrieval_ks",
        nargs="+",
        type=int,
        default=[1, 3, 5, 10, 50],
    )
    parser.add_argument(
        "--quality_ks",
        nargs="+",
        type=int,
        default=[10],
    )
    parser.add_argument(
        "--quality_metrics",
        nargs="+",
        default=["relative_location", "relative_size", "lpips", "ssim"],
        help=(
            "Subset of relative_location relative_size bbox_iou lpips ssim "
            "mae wasserstein, or use 'all'/'none'."
        ),
    )
    parser.add_argument("--lpips_net", type=str, default="alex")
    parser.add_argument("--lpips_batch_size", type=int, default=64)
    parser.add_argument("--asr_cf", action="store_true")
    parser.add_argument("--query_threshold", type=float, default=0.1)
    parser.add_argument("--database_threshold", type=float, default=0.9)
    parser.add_argument("--max_queries", type=int, default=None)
    parser.add_argument("--force", action="store_true")
    return parser.parse_args()


def default_query_file(database_dir, args):
    if args.mode == "one":
        name = (
            f"query_tokens_mode-one_nregion-1_"
            f"perregion-{args.n_samples}.pkl"
        )
    elif args.mode == "multi":
        name = (
            f"query_tokens_mode-multi_nregion-{args.n_regions}_"
            f"nquery-{args.n_queries}.pkl"
        )
    else:
        name = f"query_tokens_mode-full_nquery-{args.n_queries}.pkl"
    return database_dir / name


def load_query_representations(path):
    path = Path(path)
    if path.suffix != ".pkl":
        raise ValueError(
            "RCAT query representations must be a .pkl file generated by "
            "C2.ExtractQueryEmbeddings.py."
        )

    with open(path, "rb") as f:
        return pickle.load(f)


def resolve_quality_config(requested):
    requested = [item.lower() for item in requested]

    if "none" in requested:
        return {name: False for name in QUALITY_METRICS.values()}
    if "all" in requested:
        return {name: True for name in QUALITY_METRICS.values()}

    unknown = sorted(set(requested) - set(QUALITY_METRICS.keys()))
    if unknown:
        raise ValueError(f"Unknown quality metrics: {unknown}")

    return {
        config_name: key in requested
        for key, config_name in QUALITY_METRICS.items()
    }


def resolve_device(config, override=None):
    if override is not None:
        return torch.device(override)
    if torch.cuda.is_available():
        if getattr(config, "device", None):
            return torch.device(f"cuda:{int(config.device[0])}")
        return torch.device("cuda")
    return torch.device("cpu")


def same_volume_exclusions(query_slicename, db_filenames):
    query_volume = get_volume_id_from_slice_id(query_slicename)
    return {
        str(filename)
        for filename in db_filenames
        if get_volume_id_from_slice_id(str(filename)) == query_volume
    }


def main():
    args = parse_args()
    config = OmegaConf.load(args.config)
    device = resolve_device(config, args.device)

    database_dir = Path(
        args.database_dir or f"./results/{config.project_name}"
    )
    query_file = Path(
        args.query_file or default_query_file(database_dir, args)
    )

    with open(args.database_index, "r") as f:
        database_index = json.load(f)

    query_representations = load_query_representations(query_file)
    query_index = build_query_index_from_database_index(
        database_index=database_index,
        selected_query_organs=query_representations,
    )

    token_path = database_dir / "slice_tokens.npy"
    if not token_path.exists():
        raise FileNotFoundError(f"Database tokens not found: {token_path}")

    database_tokens_np = np.load(token_path)
    database_tokens = torch.from_numpy(database_tokens_np).to(
        device=device,
        dtype=torch.float16 if device.type == "cuda" else torch.float32,
    )

    with open(database_dir / "slice_keys.json", "r") as f:
        db_filenames = np.asarray(json.load(f), dtype=str)

    if database_tokens.shape[0] != len(db_filenames):
        raise RuntimeError("Database token/key count mismatch.")

    db_asr_flags = None
    if args.asr_cf:
        asr_path = database_dir / "slice_asr_probs.npy"
        if not asr_path.exists():
            raise FileNotFoundError(
                "ASR-CF requested, but database ASR probabilities were not found."
            )

        database_asr_probs = np.load(asr_path)
        if database_asr_probs.ndim != 3 or database_asr_probs.shape[-1] != 3:
            raise ValueError(
                "Expected database ASR probabilities with shape [N, O, 3]."
            )

        db_asr_flags = torch.from_numpy(
            database_asr_probs[..., 2] >= args.database_threshold
        ).to(device=device)

    quality_config = resolve_quality_config(args.quality_metrics)

    suffix = "asr-cf" if args.asr_cf else "base"
    result_stem = (
        f"mode-{args.mode}_nregion-{args.n_regions}_{suffix}"
    )
    retrieval_result_path = database_dir / f"retrieval_{result_stem}.pkl"
    metric_df_path = database_dir / f"metrics_{result_stem}.csv"
    summary_path = database_dir / f"summary_{result_stem}.csv"

    if retrieval_result_path.exists() and not args.force:
        print(f"Loading cached retrieval results: {retrieval_result_path}")
        with open(retrieval_result_path, "rb") as f:
            retrieval_results = pickle.load(f)
    else:
        retrieval_results = {}
        query_keys = list(query_representations.keys())
        if args.max_queries is not None:
            query_keys = query_keys[: args.max_queries]

        for query_key in tqdm(query_keys, desc="RCAT retrieval"):
            q_info = query_representations[query_key]
            query_idx = [int(x) for x in q_info["query_idx"]]
            query_tokens = q_info["anatomical_tokens"]
            selectivity_weights = q_info["selectivity_weights"]

            query_slicename, _ = parse_gallery_query_key(query_key)
            excluded_filenames = same_volume_exclusions(
                query_slicename,
                db_filenames,
            )

            topk_filenames, topk_scores, topk_indices, elapsed = retrieve_topk(
                query_tokens=query_tokens,
                database_tokens=database_tokens,
                selectivity_weights=selectivity_weights,
                db_filenames=db_filenames,
                topk=len(db_filenames),
                db_asr_flags=db_asr_flags,
                query_selectivity_threshold=args.query_threshold,
                exclude_filenames=excluded_filenames,
                time_check=True,
            )

            retrieval_results[query_key] = {
                "query_slice": query_slicename,
                "query_key": query_key,
                "query_idx": query_idx,
                "topk_filenames": topk_filenames.tolist(),
                "topk_scores": topk_scores.tolist(),
                "topk_indices": topk_indices.tolist(),
                "excluded_filenames": sorted(excluded_filenames),
                "retrieval_time_sec": float(elapsed),
            }

        with open(retrieval_result_path, "wb") as f:
            pickle.dump(
                retrieval_results,
                f,
                protocol=pickle.HIGHEST_PROTOCOL,
            )
        print(f"Saved retrieval results: {retrieval_result_path}")

    if metric_df_path.exists() and not args.force:
        print(f"Loading cached metrics: {metric_df_path}")
        metric_df = pd.read_csv(metric_df_path)
    else:
        metric_df = evaluate_all_queries(
            retrieval_results=retrieval_results,
            query_index=query_index,
            database_index=database_index,
            ks=args.retrieval_ks,
            quality_ks=args.quality_ks,
            quality_config=quality_config,
            lpips_net=args.lpips_net,
            lpips_batch_size=args.lpips_batch_size,
            img_size=(128, 128),
            area_key="foreground_relative_area",
            centroid_key="foreground_relative_centroid",
            missing_policy="skip",
        )

        time_by_query = {
            key: value.get("retrieval_time_sec", np.nan)
            for key, value in retrieval_results.items()
        }
        metric_df["retrieval_time_sec"] = metric_df["query_slice"].map(
            time_by_query
        )

        # Keep the original metric columns while also exposing the paper names.
        for k in args.quality_ks:
            if f"SSIM@{k}" in metric_df.columns:
                metric_df[f"SSIM_rel@{k}"] = metric_df[f"SSIM@{k}"]
            if f"LPIPS@{k}" in metric_df.columns:
                metric_df[f"LPIPS_rel@{k}"] = metric_df[f"LPIPS@{k}"]

        metric_df.to_csv(metric_df_path, index=False)
        print(f"Saved query-level metrics: {metric_df_path}")

    organ_summary, macro_summary = summarize_metrics_by_organ(
        metric_df,
        ks=args.retrieval_ks,
    )
    summary_by_type = summarize_metrics_by_type(
        organ_summary,
        ks=args.retrieval_ks,
    )
    summary_by_type.to_csv(summary_path, index=False)

    overall = metric_df.mean(numeric_only=True)
    print("\nOverall query-level mean")
    for name in ["P@1", "P@10", "AP@10", "SSIM_rel@10", "LPIPS_rel@10"]:
        if name in overall.index:
            label = "mAP@10" if name == "AP@10" else name
            print(f"{label}: {overall[name]:.6f}")

    times = metric_df.get("retrieval_time_sec")
    if times is not None and len(times) > 0:
        warm = times.iloc[min(10, len(times)):].dropna()
        if len(warm) > 0:
            print(f"Mean retrieval time after 10 warm-up queries: {warm.mean():.6f} s")

    print("\nMacro summary over query-region groups")
    print(summary_by_type.to_string(index=False))
    print(f"\nSaved summary: {summary_path}")


if __name__ == "__main__":
    main()
